### ISSUE TITLE
SF Inspector with a Connected App in Firefox

### ISSUE THREAD

**Issue by kkorynta** [tprouvot/Salesforce-Inspector-reloaded#137]
**Is your feature request related to a problem? Please describe.**
We have API access controls in salesforce where we force users to authenticate through a Connected App. Our Firefox users are unable to authenticate following similar instructions here: https://github.com/tprouvot/Salesforce-Inspector-reloaded/wiki/How-to#use-sf-inspector-with-a-connected-app

**Describe the solution you'd like**
I'd like for our Firefox users to be able to continue to use their browser of choice. 

**Describe alternatives you've considered**
Alternative is to force them into Chrome.

**Additional context**
It looks like firefox "extension Ids" are different per user/machine.

**Comment by tprouvot** [comment]
Hi @kkorynta,
I'll check tomorrow if I can make it work with Firefox, could you share the extension Id for you ? I'll compare it to mine tomorrow

**Comment by kkorynta** [comment]
@tprouvot 
When I go to the Data Export tab, this is what appears:
moz-extension://7d3f32d2-10c4-4fc0-a854-8d4e659b4c0a/data-export.html?host=<orgdomain>.my.salesforce.com

One of the users I was testing with had this produced:
moz-extension://85a2a7d4-af97-447d-a195-cadcfa2eb425/data-export.html?host=<orgdomain>.my.salesforce.com

If I hit generate token, I get this interesting URL:
https://<orgdomain>.my.salesforce.com/services/oauth2/authorize?
response_type=token
&client_id=<clientId>
&redirect_uri=
chrome-extension://salesforceinspector@reloaded/data-export.html?host=<orgdomain>.my.salesforce.com%26

**Comment by tprouvot** [comment]
Hi @kkorynta,
I have the same behaviour as yours, the extension id changes depending on the user's installation.

I updated the extension on the firefox store and tried to set an extension id without success.
It looks like we can't have a unique extension id on firefox, I have to explore other options.

And you're right, the redirect url contains "chrome-extension" since the functionality was designed only on chrome so I have to detect browser to build the url.

From now I have no other solution to migrate to chrome.

**Comment by tprouvot** [comment]
Hi @kkorynta,
I [fixed](https://github.com/tprouvot/Salesforce-Inspector-reloaded/commit/d6f94381305165b7d994ae7eee5e8ff495f1ba90) the hardcoded part, which opens a new **dirty** workaround depending on your team size.

Now the generate token url is fixed, you would be able to create a connected app for each user (since we have different extension id for each install)
What size is your team ? 

FYI the fixed is not deployed on the firefox store but can be if this workaround suits your for the moment

**Comment by kkorynta** [comment]
The full team is about 15-20 users + folks on the finance side of the house. There's maybe about 5 of them that use Firefox. 

With this workaround, could we have multiple callback URLs listed instead of a connected app for each user? That's how I configured the Chrome side of it to work for each of our pipeline environments. 

If we could swing that, then that would work. We can just document the Ids for now and then inform them of what happens if they uninstall.

**Comment by tprouvot** [comment]
Yep that could work 👍
I'll release the new version at the beginning of the week and update related documentation for Firefox if it works !

**Comment by kkorynta** [comment]
You're the best. Tyvm!!

**Comment by tprouvot** [comment]
Hey @kkorynta,
I've submitted the new version on firefox store, it should be available during the day ! 🚀

**Comment by tprouvot** [comment]
@kkorynta  Extension updated on the store 
<img width="389" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/3a18dc84-03c3-4888-b64b-dc88584283cc">
