### ISSUE TITLE
Delete records can result in about: blocked page

### ISSUE THREAD

**Issue by natel628** [tprouvot/Salesforce-Inspector-reloaded#249]
**Is your feature request related to a problem? Please describe.**
If I run a query that returns 100,000 records and click delete, it opens a blank page
**Describe the solution you'd like**
Be able to delete them as if the query returns 10
**Describe alternatives you've considered**
Copy to excel > import option> delete
**Additional context**

**Comment by tprouvot** [comment]
Hi @natel628,
Since the button is available I understand that it can be tempting to use it but this is not designed for large volumes.
Inspector relies on copy paste for data export and those volumes implies a large use of the OS clipboard which can lead to  application crashes.

I think I'll disable the button for queries that returns more than 2k records

**Comment by tprouvot** [comment]
https://github.com/tprouvot/Salesforce-Inspector-reloaded/commit/ab365d17cef48c52e7ec97436fcc5c997291589a
