### ISSUE TITLE
Allow to set the button location so that it does not interfere

### ISSUE THREAD

**Issue by Manu2pace** [tprouvot/Salesforce-Inspector-reloaded#310]
Sometimes the button placement is on top of other Salesforce UI element. This is especially true when working with flows 
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/116733084/babc5d52-466e-4f25-9b5b-f779ef7da19b)

It would be great if it was possible to parameter the location along the adge of the screen. This could ebe done by changing the css top calculation to take this new parameter into consideration : 
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/116733084/79f89d4d-0b94-4226-9e8c-3303f8483ea9)

This feature is available in [organizer](https://organizer.solutions/index.html#page-top) 
<img width="721" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/116733084/fc040a76-9b51-4e67-94fe-a10528ec91e4">

**Comment by tprouvot** [comment]
Hi @Manu2pace,

This has been requested in[ another feature request](https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/200) which is closed because it is already developed.

You can already test it by installing the [beta version](https://chromewebstore.google.com/detail/salesforce-inspector-relo/lopjgjcglnncikiocpacfdbkmpbfmkcf). The main version should be released by the end of the month
