### ISSUE TITLE
[show-all-data] When double clicking on an empty picklist field, iterate through avaible values

### ISSUE THREAD

**Issue by tprouvot** [tprouvot/Salesforce-Inspector-reloaded#366]
**Is your feature request related to a problem? Please describe.**
On inspect page, when double clicking on an empty picklist field, iterate through available values with up and down keys.

<img width="714" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/f13cbab7-d19a-4771-a97d-95498b451718">

We could also set a placeholder to show users the first values and the functionality

**Comment by tprouvot** [comment]
Hi @megmoo,
No it doesn't require Summer 24', are you on the 1.23 ?

**Comment by megmoo** [comment]
@tprouvot - Yes. I'm on 1.23. I tried with a new profile on only SF Inspector Reloaded installed and it did not work that way, either. 

Just to make sure I'm not doing anything stupid, I'm pressing the ctrl button and the alt button and the i button, correct?

**Comment by tprouvot** [comment]
@megmoo Nope, you have to press up or down key to iterate on the values

**Comment by megmoo** [comment]
But that would only be once the extension is open, right? Once I'm in the extension, I use the up/down to iterate the values, but is there any way to get the extension to open using hotkeys? I'm trying to avoid having to click on up there. I interpreted the text at the bottom as ctrl+alt+i will open the extension.

[ctrl+alt+i] to open

**Comment by tprouvot** [comment]
@megmoo Does your question is about the iteration functionality? 
Because that is what I understood from your first question. 
But reading your last comment it seems that you are talking about the popup opening so I'm confused 😕

**Comment by megmoo** [comment]
@tprouvot  - Sorry I was unclear. Perhaps a better way to approach it is this: at the bottom of the extension pop-out, there's small text that says: _[ctrl+alt+i] to open_

My assumption was that the hot key combination ctrl+alt+i would make the extension pop-out (and hopefully set focus on the input field where the red arrow in the screen shot is pointing). 

It seems my assumption must be wrong. In that case, two questions: 
1. What is [ctrl+alt+i] supposed to open?
2. Is there any way, currently, to make the extension pop-up and set focus in the input field so that a mouse click isn't required to use it? 

Thank you in advance!

![Salesforce Inspector](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/53194056/1254b245-9451-4ad7-8d07-533a692329ed)

**Comment by RebbePod** [comment]
This is great!!
Would love for a way to do it with a mouse click as well
