### ISSUE TITLE
Can't search for Person Account object on Objects tab

### ISSUE THREAD

**Issue by brittsfadmin** [tprouvot/Salesforce-Inspector-reloaded#427]
When using the Inspector Reloaded in an org with Person Accounts enabled, and using the search bar located on the Objects tab, Person Accounts is not able to be selected.

**To Reproduce**
1. Enable Person Accounts in the org, or login to an org with Person Accounts enabled
2. Go to 'Objects' tab in the Inspector Reloaded
3. Click on 'search bar'
4. Type in 'Person Account' both with and without the space
5. Search for the Person Accounts standard object, and see that it is not available.

**Expected behavior**
Would expect to be able to select the Person Account object

**Screenshots**
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/169720971/32887641-4f81-4bd4-b54e-1219d255e3df)
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/169720971/808d5b21-36fa-4f31-8d79-1627e8eb6930)
![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/169720971/b057c8ef-46f3-4dbe-a3a0-599995b36f98)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome (Version 124.0.6367.202 (Official Build) (64-bit))
 - Version: 1.23.1

**Additional context**
Wouldn't be able to select the Fields on this object as they're all located on the actual Account object, but would be good to navigate to the Record Types

**Comment by tprouvot** [comment]
Hi @brittsfadmin,

That's because PersonAccount is not a proper SObject and not returned in the EntityDefinition.

What you could do is to create a custom shortcut for PersonAccount recordtype:

By code :
Open chrome dev console from data-export page

<img width="961" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/d6be1d24-1d37-499f-8904-56a31ba66c6a">


Then paste following code in the console 

![image](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/184ea4aa-d8a9-4e69-b445-bfbd1d680c0e)

``` js
let rcLink = {
    "label": "PersonAccount RecordType",
    "section": "Custom",
    "link": "/lightning/setup/ObjectManager/PersonAccount/RecordTypes/view",
    "prod": false
};

const urlParams = new URLSearchParams(window.location.search);
const sfHost = urlParams.get('host');

let links = localStorage.getItem(sfHost + "_orgLinks") ? JSON.parse(localStorage.getItem(sfHost + "_orgLinks")) : [];
links.push(rcLink);
localStorage.setItem(sfHost + "_orgLinks", JSON.stringify(links));
``` 
<img width="275" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/8e743779-03ac-481e-964d-ba807049fd3a">


or [manually](https://tprouvot.github.io/Salesforce-Inspector-reloaded/how-to/#add-custom-links-to-shortcut-tab)
