### ISSUE TITLE
User Permissions - Feature to limit users ability to import data 

### ISSUE THREAD

**Issue by jaderybalko** [tprouvot/Salesforce-Inspector-reloaded#451]
**Describe the solution you'd like**
I'd like a way to restrict a user from importing data while allowing them to export. I want to keep their permissions as is in Salesforce so they can edit a record or field directly from the website instead of mass importing from the extension. 

**Describe alternatives you've considered**
The only solution I can think of currently is updating their permissions in salesforce to read only.

**Comment by tprouvot** [comment]
Hi @jaderybalko ,
Have you checked this [section](https://tprouvot.github.io/Salesforce-Inspector-reloaded/how-to/#use-sf-inspector-with-a-connected-app)  which allows you to choose which user can use Reloaded ?

Because based on your comment if you want to restrict the usage of mass import, it should not be only on reloaded but on all chrome extensions and external tools (ie dataloader).
To me the best way is to enable API Access Control
