### ISSUE TITLE
[beta] Link to object KO for custom settings

### ISSUE THREAD

**Issue by tprouvot** [tprouvot/Salesforce-Inspector-reloaded#473]
**Make sure to read the troubleshooting section before creating an issue**
In the popup, the link Object List is supposed to redirect to the list of the custom settings and not the standard url.

- [ ] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, firefox, edge]
 - Version [e.g. 1.20]

**Additional context**

**Comment by tprouvot** [comment]
Closed in https://github.com/tprouvot/Salesforce-Inspector-reloaded/pull/477

**Comment by PedroPTavaresJr** [comment]
The latest release notes mentio that this was delivered.
Since the updated was installed on my machine, the popup vanished all toghether, could not be related, but since it involves the popup.

It is back when using the beta version of the extension.

**OS:** Windos 11 build 22631.4037
**Browser:** Chrome / Version 128.0.6613.85 (Official Build) (64-bit)
**Salesforce Inspector reloaded:** 1.24
**Salesforce Inspector Reloaded BETA:** 1.24 beta

**Comment by tprouvot** [comment]
Hi @PedroPTavaresJr ,
The issue is not related to this feature but you can find the info here
https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/535
