### ISSUE TITLE
[data-export] Autocomplete Field Names

### ISSUE THREAD

**Issue by energidi** [tprouvot/Salesforce-Inspector-reloaded#548]
It would be great if an autocomplete feature suggested field names alphabetically as you type, instead (or in addition) of having to select the field name from a list below.

**Comment by tprouvot** [comment]
Hi @energidi,
It would be great to have more context 😄 more important I think is : which page are you talking about ? Could you explain with screenshots ? 

Best would have been to follow up the template:

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by energidi** [comment]
Sorry for not being clear.
I'm referring to the 'Data Export' feature.
![2024-09-02_17-06-24](https://github.com/user-attachments/assets/776503a5-5308-4c29-90bc-c227322fce87)
It would be great if an autocomplete feature suggested field names alphabetically as you type the query, instead (or in addition) of having to select the field name from a list below.
Please see the attached screenshot as an example.
![Exmple for Autocomplete Fields](https://github.com/user-attachments/assets/9754bd12-438e-47e2-8ae8-7da0467b5451)

**Comment by tprouvot** [comment]
Thanks for adding the info, it is clearer now.
Before considering a new feature, are you aware of the shortcuts to select the suggested fields from the autocomplete list ?

<img width="547" alt="image" src="https://github.com/user-attachments/assets/668fd5a2-1970-42eb-b8a4-729e7fbd0b88">

In this case, press tab and enter to select the field and get your cursor back on the query

<img width="309" alt="image" src="https://github.com/user-attachments/assets/4e9e04ed-3af2-4746-ab8d-d38510ac3317">

**Comment by energidi** [comment]
Hello @tprouvot 
Thank you for letting me know!
I wasn't aware of this feature. 
While I find that autocomplete for fields as in the provided example makes typing easier, the existing feature is still quite satisfying.
Thanks again for such a useful app!
