### ISSUE TITLE
[field-creator] API name should use underscores

### ISSUE THREAD

**Issue by sqone2** [tprouvot/Salesforce-Inspector-reloaded#655]
The new field creator solution is great, but can we please have an option to replace spaces with underscores instead of removing them completely? This way the functionality will match the out of the box field creation wizard.

Current Behavior:
<img width="1472" alt="image" src="https://github.com/user-attachments/assets/208c16cd-f0d7-4544-9484-e7ba198e0859">

Suggested Update:
<img width="1541" alt="image" src="https://github.com/user-attachments/assets/552f471b-7973-42b7-a21a-eadeaecd72f0">

**Comment by tprouvot** [comment]
Hi @sqone2,

That's funny to see the differences between user habits and naming conventions.
Initially Santiago who developed this feature used the underscore to match the standard behavior and I asked him to switch to Pascal case instead of underscores 😊
You'll understand that I'm not from the underscore team! 
That being said my intention was to prevent this usage as standard behavior, I understand that there might be particular use cases or project conventions that rely on a legacy that should be kept. 
I'll check with Santiago what can be done in the options.

**Comment by tprouvot** [comment]
I think I would rather choose a picklist with "PascalCase" or "Underscore" values to make it cristal clear.
I'm still annoyed by this convention and try to find good reasons to use it ... 😄 
What is yours ?

**Comment by tprouvot** [comment]
@sqone2 Would you like to code this by your own ? 
I assume you are a dev from your other feature request about the default query height

**Comment by tprouvot** [comment]
Great ! You can take a look at the [contribution section](https://github.com/tprouvot/Salesforce-Inspector-reloaded?tab=readme-ov-file#contributions ).
