### ISSUE TITLE
JSON format record import

### ISSUE THREAD

**Issue by gaelguimini** [tprouvot/Salesforce-Inspector-reloaded#75]
**Is your feature request related to a problem? Please describe.**
As an admin would love to be able to import data based on JSON format.

**Describe the solution you'd like**
Since i can export records as JSON, i can then use JS scripting to alter records any way i want.
I then would love to be able to re-import them.

**Describe alternatives you've considered**
For now, i need to script a CSV export for said record. it causes unnecessary work, and issues with escaping chars (line breaks, commas, and so on).

**Additional context**
It would also circumvent an issue i opened on legacy repo 
https://github.com/sorenkrabbe/Chrome-Salesforce-inspector/issues/248

**Comment by tprouvot** [comment]
Hi @gaelguimini thanks for creating this request !
When you're saying 'Since i can export records as JSON' you're talking about sfdx command ? SFDMU ? 

To me, since you're exporting the data with a particular tool, you should be able to re-import it with the same tool.
Can you explain your use case ?

**Comment by gaelguimini** [comment]
Hi,

I mean within the SFI-reloaded chrome ext, data export offers to copy data as XLS, CSV & JSON formats.
However, Import feature only allows for CSV and XLS format imports.

This feature request is purely independent of 3rd party tools and just rely on the consistency of supported format within the extension.

Uses cases where this would be applicable : 
* (3rd party to SFI-reloadded) Customer provides me with a JSON export of their legacy tools for migration to salesforce. I then script a tranformation to Salesforce model, outputting JSON. For now, i also need to script a CSV export, which has its own issues.
* (SFI-relaoded to sfi-reloaded) After a change of model, i need to transform data. I could export records with the extension, script whatever i need and output JSON for reimport. 

I hope this is a bit clearer now :)
cheers,

**Comment by tprouvot** [comment]
Hi @gaelguimini,

Could you locally test the new functionality by checking out the branch https://github.com/tprouvot/Salesforce-Inspector-reloaded/tree/feat/importAsJSON ?

If not could you provide some export so that I could test it ?
I tested the import with following query:
`SELECT Id , Name FROM Contact LIMIT 10 `

**Comment by tprouvot** [comment]
Will be part of the next release v1.17, is available for local test in the releaseCandidate branch
