### ISSUE TITLE
[data-export] Entity Name in column Owner instead of User

### ISSUE THREAD

**Issue by pinogalati** [tprouvot/Salesforce-Inspector-reloaded#95]
**Describe the bug**
Performing a SOQL query via Export, with lookup field to user in SELECT return Error No such Column 'xxx' on entity 'Name'.

**To Reproduce**
1. Open the extension
2. Execute the following query "SELECT Owner.Id, Owner.Name FROM VoiceCall"
3. Scroll down to the result;
4. In the Owner column you can see 'Name' instead of 'Owner' and if i try to open the owner record by clicking Name i receive "NOT_FOUND: The requested resource does not exist" Name (Name /);
5. If I perform the same query on the Contact Object "SELECT Owner.Id, Owner.Name FROM Contact", in the Owner column you can see 'User' (and NOT Name like above) and if i try to open the owner record by clicking User it works fine.

**Expected behavior**
The Owner column must have the lookup to a User object and NOT to a Name object.

**Screenshots**
Screen 1 - VoiceCall object - with error
![Screenshot 2023-05-16 at 15 15 23](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/19263656/a51fbbdc-0aab-4962-aced-728b84a0d8cd)

Screen 2 - Contact object - without error
![Screenshot 2023-05-16 at 15 15 13](https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/19263656/122957f2-d969-4beb-b544-f1b76fc97678)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 113.0.5672.92

**Comment by tprouvot** [comment]
Hi @pinogalati ,

That's because the OwnerId field is polymorphic for VoiceCall object (and can be a User **OR** a Group) and the OwnerId on Contact can only be a User:

<img width="810" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/bf17de90-fffa-4929-b9f2-dcf43217daaa">
<img width="797" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/aa3dde3b-8957-43c7-9d15-fa0d697d5d86">

**Comment by tprouvot** [comment]
Hi @pinogalati ,

I've just checked and the Entity type comes from Salesforce rest response, no action to perform from the extension.

<img width="1139" alt="image" src="https://github.com/tprouvot/Salesforce-Inspector-reloaded/assets/35368290/0ec96223-9f2b-4462-a806-d653e412fa9c">
